name: auto-mod-fx-v7
env:    
  TZ: America/Sanfransisco  
on:
  workflow_dispatch:
  schedule:
    - cron: "5  8  *  *  0"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Download and mod fenix
      run: |
        wget -q -O "resp64m" https://download-ssl.firefox.com.cn/releases/mobile/90.1/zh-CN/Firefox-Android-90.1.apk
        wget -q https://github.com/iBotPeaches/Apktool/releases/download/v2.5.0/apktool_2.5.0.jar
        
        
        java -jar apktool_2.5.0.jar d resp64m -o v8a
        
        sed -i "s/^.*versionCode.*$/  versionCode: '2147483647'/" v8a/apktool.yml
        sed -i 's/baidu/unknown/g' v8a/assets/extensions/webcompat/data/ua_overrides.js
        sed -i 's/browser.safebrowsing.malware.enabled/unknown/;s/browser.safebrowsing.phishing.enabled/unknown/' v8a/smali_classes2/org/mozilla/geckoview/ContentBlocking\\\$Settings.smali
        sed -i '/public aboutConfigEnabled/{n;s/\.locals 1/\.locals 1\n      const\/4 p1, 0x1/}' v8a/smali_classes2/org/mozilla/geckoview/GeckoRuntimeSettings\\\$Builder.smali
        sed -i 's/"geckoViewAddons"/"unknown"/;s/"nativeMessaging"/"unknown"/;/invoke-virtual {p0, p1, p2, p3}/i\    const\/4 p2, 0x1' v8a/smali/mozilla/components/feature/addons/AddonManager.smali
        sed -i 's/"content"/"unknown"/;s/"file"/"unknown"/;s/"resource"/"unknown"/' v8a/smali/mozilla/components/browser/engine/gecko/GeckoEngineSession.smali
        sed -i 's/^.*iget-boolean.*showSecretDebugMenuThisSession:Z$/    const\/4 v0, 0x1/' v8a/smali_classes2/org/mozilla/fenix/utils/Settings.smali
        sed -i 's/const\/4 v0, 0x0/const\/4 v0, 0x1/g' v8a/smali/org/mozilla/fenix/ReleaseChannel.smali
        sed -i 's/"mozilla"/"lindongbin"/g;s/7dfae8669acc4312a65e8ba5553036/fenix/g' v8a/smali_classes2/org/mozilla/fenix/components/Components\\\$addonCollectionProvider\\\$2.smali
        sed -i 's/"-popularity"/"name"/' v8a/smali/mozilla/components/feature/addons/amo/SortOption.smali 
        java -jar apktool_2.5.0.jar b v8a -o v8a.apk --use-aapt2
        wget -q https://github.com/lindongbin/gt/raw/master/zipalign
        wget -q -P ./lib64 https://github.com/lindongbin/gt/raw/master/libc%2B%2B.so
        chmod +x zipalign
        ./zipalign -p 4 v8a.apk v8a-align.apk
        
        wget -q https://github.com/lindongbin/gt/raw/master/apksigner.jar
        wget -q https://github.com/lindongbin/gt/raw/master/apksigner.jks
        java -jar apksigner.jar sign --ks apksigner.jks --ks-pass pass:testkey --out fxc-m-7a.apk v8a-align.apk
        mkdir arm64
        mv fxc-m-7a.apk ./arm64/
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +%Y年%m月%d日%H时)"
    - name: Upload fxn-v8 release
      uses: svenstaro/upload-release-action@v2
      with:           
        repo_token: ${{ secrets.ACTION_TOKEN }}
        file: ./arm64/fxc-m-7a.apk
        tag: ${{ steps.date.outputs.date }}           
        body: "Chinese Version"           
        file_glob: true           
        prerelease: false           
        overwrite: true

