name: auto-mod-fxn-all

on:
  workflow_dispatch:
  schedule:
    - cron: "18 16,4  *  *  *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Download and mod fenix
      run: |
        wget -q -O "resp32m" https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.nightly.latest.arm64-v8a/artifacts/public/build/armeabi-v7a/target.apk
        wget -q -O "resp64m" https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.nightly.latest.arm64-v8a/artifacts/public/build/arm64-v8a/target.apk
        wget -q -O "resp64p" https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.nightly.latest.arm64-v8a/artifacts/public/build/x86_64/target.apk
        wget -q -O "resp32p" https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.nightly.latest.arm64-v8a/artifacts/public/build/x86/target.apk
        wget -q https://github.com/iBotPeaches/Apktool/releases/download/v2.5.0/apktool_2.5.0.jar
        
        
        java -jar apktool_2.5.0.jar d resp32m -o v7a
        java -jar apktool_2.5.0.jar d resp64m -o v8a
        java -jar apktool_2.5.0.jar d resp32p -o v7p
        java -jar apktool_2.5.0.jar d resp64p -o v8p
        
        sed -i 's/browser.safebrowsing.malware.enabled/unknown/;s/browser.safebrowsing.phishing.enabled/unknown/' v8a/smali_classes2/org/mozilla/geckoview/ContentBlocking\$Settings.smali
        sed -i 's/android\/downloads/firefox\/downloads/' v8a/smali_classes2/org/mozilla/fenix/AppRequestInterceptor.smali
        sed -i 's/if-eqz p1, :cond_c/goto :cond_c/' v8a/smali/mozilla/components/feature/addons/ui/AddonsManagerAdapter.smali
        sed -i 's/"geckoViewAddons"/"unknown"/;s/"nativeMessaging"/"unknown"/' v8a/smali/mozilla/components/feature/addons/AddonManager.smali
        sed -i '/.line 9/i\ const-string v5, "https:\/\/cdn.jsdelivr.net\/gh\/Rosabis\/01@addons\/addons.json"' v8a/smali/mozilla/components/feature/addons/amo/AddonCollectionProvider.smali
        sed -i 's/"content"/"unknown"/;s/"file"/"unknown"/;s/"resource"/"unknown"/' v8a/smali/mozilla/components/browser/engine/gecko/GeckoEngineSession.smali
        sed -i 's/browser.safebrowsing.malware.enabled/unknown/;s/browser.safebrowsing.phishing.enabled/unknown/' v7a/smali_classes2/org/mozilla/geckoview/ContentBlocking\$Settings.smali
        sed -i 's/android\/downloads/firefox\/downloads/' v7a/smali_classes2/org/mozilla/fenix/AppRequestInterceptor.smali
        sed -i 's/if-eqz p1, :cond_c/goto :cond_c/' v7a/smali/mozilla/components/feature/addons/ui/AddonsManagerAdapter.smali
        sed -i 's/"geckoViewAddons"/"unknown"/;s/"nativeMessaging"/"unknown"/' v7a/smali/mozilla/components/feature/addons/AddonManager.smali
        sed -i '/.line 9/i\ const-string v5, "https:\/\/cdn.jsdelivr.net\/gh\/Rosabis\/01@addons\/addons.json"' v7a/smali/mozilla/components/feature/addons/amo/AddonCollectionProvider.smali
        sed -i 's/browser.safebrowsing.malware.enabled/unknown/;s/browser.safebrowsing.phishing.enabled/unknown/' v8p/smali_classes2/org/mozilla/geckoview/ContentBlocking\$Settings.smali
        sed -i 's/android\/downloads/firefox\/downloads/' v8p/smali_classes2/org/mozilla/fenix/AppRequestInterceptor.smali
        sed -i 's/if-eqz p1, :cond_c/goto :cond_c/' v8p/smali/mozilla/components/feature/addons/ui/AddonsManagerAdapter.smali
        sed -i 's/"geckoViewAddons"/"unknown"/;s/"nativeMessaging"/"unknown"/' v8p/smali/mozilla/components/feature/addons/AddonManager.smali
        sed -i '/.line 9/i\ const-string v5, "https:\/\/cdn.jsdelivr.net\/gh\/Rosabis\/01@addons\/addons.json"' v8p/smali/mozilla/components/feature/addons/amo/AddonCollectionProvider.smali
        sed -i 's/"content"/"unknown"/;s/"file"/"unknown"/;s/"resource"/"unknown"/' v8p/smali/mozilla/components/browser/engine/gecko/GeckoEngineSession.smali
        sed -i 's/browser.safebrowsing.malware.enabled/unknown/;s/browser.safebrowsing.phishing.enabled/unknown/' v7p/smali_classes2/org/mozilla/geckoview/ContentBlocking\$Settings.smali
        sed -i 's/android\/downloads/firefox\/downloads/' v7p/smali_classes2/org/mozilla/fenix/AppRequestInterceptor.smali
        sed -i 's/if-eqz p1, :cond_c/goto :cond_c/' v7p/smali/mozilla/components/feature/addons/ui/AddonsManagerAdapter.smali
        sed -i 's/"content"/"unknown"/;s/"file"/"unknown"/;s/"resource"/"unknown"/' v8a/smali/mozilla/components/browser/engine/gecko/GeckoEngineSession.smali
        sed -i 's/"geckoViewAddons"/"unknown"/;s/"nativeMessaging"/"unknown"/' v7p/smali/mozilla/components/feature/addons/AddonManager.smali
        sed -i '/.line 9/i\ const-string v5, "https:\/\/cdn.jsdelivr.net\/gh\/Rosabis\/01@addons\/addons.json"' v7p/smali/mozilla/components/feature/addons/amo/AddonCollectionProvider.smali
        sed -i 's/"content"/"unknown"/;s/"file"/"unknown"/;s/"resource"/"unknown"/' v7p/smali/mozilla/components/browser/engine/gecko/GeckoEngineSession.smali
        java -jar apktool_2.5.0.jar b v7a -o v7a.apk --use-aapt2
        java -jar apktool_2.5.0.jar b v8a -o v8a.apk --use-aapt2
        java -jar apktool_2.5.0.jar b v7p -o v7p.apk --use-aapt2
        java -jar apktool_2.5.0.jar b v8p -o v8p.apk --use-aapt2
        wget -q https://github.com/Rosabis/01/raw/master/zipalign
        wget -q -P ./lib64 https://github.com/Rosabis/01/raw/master/libc%2B%2B.so
        chmod +x zipalign
        ./zipalign -p 4 v7a.apk v7a-align.apk
        ./zipalign -p 4 v8a.apk v8a-align.apk
        ./zipalign -p 4 v7p.apk v7p-align.apk
        ./zipalign -p 4 v8p.apk v8p-align.apk
        
        wget -q https://github.com/Rosabis/01/raw/master/apksigner.jar
        wget -q https://github.com/Rosabis/01/raw/master/apksigner.jks
        java -jar apksigner.jar sign --ks apksigner.jks --ks-pass pass:testkey --out fxn-m-7a.apk v7a-align.apk
        java -jar apksigner.jar sign --ks apksigner.jks --ks-pass pass:testkey --out fxn-m-8a.apk v8a-align.apk
        java -jar apksigner.jar sign --ks apksigner.jks --ks-pass pass:testkey --out fxn-m-7p.apk v7p-align.apk
        java -jar apksigner.jar sign --ks apksigner.jks --ks-pass pass:testkey --out fxn-m-8p.apk v8p-align.apk
        mkdir arm
        mkdir arm64
        mkdir x86
        mkdir x64
        mv fxn-m-7a.apk ./arm/
        mv fxn-m-8a.apk ./arm64/
        mv fxn-m-7p.apk ./x86/
        mv fxn-m-8p.apk ./x64/
    - name: Upload nightly release
      uses: svenstaro/upload-release-action@v2
      with:           
        repo_token: ${{ secrets.ACTION_TOKEN }}
        file: ./arm64/fxn-m-8a.apk
        tag: ${{ github.ref }}           
        body: "Nightly build"           
        file_glob: true           
        prerelease: true           
        overwrite: true
    - uses: actions/upload-artifact@v2
      with:
          name: fxn-m-v7a
          path: ./arm/
    - uses: actions/upload-artifact@v2
      with:
          name: fxn-m-v8a
          path: ./arm64/
    - uses: actions/upload-artifact@v2
      with:
          name: fxn-m-x86
          path: ./x86/
    - uses: actions/upload-artifact@v2
      with:
          name: fxn-m-x64
          path: ./x64/

